#!/usr/bin/env bash
# Install and configure a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 1211-web-01 35.196.106.109:80 check\n\tserver 1211-web-02 54.196.186.129:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
