#!/usr/bin/env bash
# FizzBuzz exercise

for ((n = 1; n <= 100; n++))
do
    if [[ $((n % 3)) -ne 0 ]] && [[ $((n % 5)) -ne 0 ]]
    then
	echo "$n"
    else
	if [[ $((n % 15)) -eq 0 ]]
	then
	    echo "FizzBuzz"
	elif [[ $((n % 3)) -eq 0 ]]
	then
	    echo "Fizz"
	elif [[ $((n % 5)) -eq 0 ]]
	then
	    echo "Buzz"
	fi
    fi
done
