#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
#but for the 9th iteration, displays Holberton School and then Hi on a new line.
n=1
while [[ $n -le 10 ]]; do
    echo "Holberton School"
    if [ $n -eq 9 ]
    then
	echo "Hi"
    fi
    n=$((n += 1))
done
