#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

n=0
while [[ $n -le 12 ]]; do
    echo "Hour: $n"
    x=0
    while [[ $x -lt 60 ]]; do
	echo $x
	x=$((x += 1))
    done
    n=$((n += 1))
done
